version: '3'
services:
  api:
    build: ./
    container_name: payment-service-provider-api
    volumes:
      - ./:/home/node/api
      - /home/node/api/node_modules
    ports:
      - '3333:3333'
    depends_on:
      - database-pg
    networks:
      - compose-network
  database-pg:
    image: postgres
    container_name: postgres-database
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - compose-network
volumes:
  pg-data:

networks:
  compose-network:
    driver: bridge
